{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Welcome to the cerf quickstarter!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "pycharm": {
     "name": "#%% md\n"
    }
   },
   "source": [
    "## A brief introduction\n",
    "\n",
    "The Capacity Expansion Regional Feasibility package (`cerf`) helps us evaluate the feasibility and structure of future electricity capacity expansion plans by siting power plants in areas that have been deemed the least cost option.  We can use `cerf` to gain an understanding of topics such as:  1) whether or not future projected electricity expansion plans from models such as GCAM are possible to achieve, 2) where suitability (e.g., cooling water availability) may influence our ability to achieve certain expansions, and/or 3) how power plant infrastructure build outs and value may evolve into the future when considering locational marginal pricing from a grid operations model.\n",
    "\n",
    "`cerf` currently operates at a 1 km<sup>2</sup> resolution over the conterminous United States.  Each grid cell is given an initial value of suitable (0) or unsuitable (1) based on a collection of suitability criteria gleaned from the literature.  `cerf`'s default suitability layers include both those that are common to all thermal technologies as well as technology-specific suitability criteria.  Common suitability layers represent categories such as protected lands, critical habitat areas, and much more.  Technology-specific suitability layers are those that satisfy requirements that may not be applicable to all technologies.  An example would be minimum mean annual flow requirements for cooling water availability for individual thermal technologies.\n",
    "\n",
    "We introduce a metric named **Net Locational Cost (NLC)** that is used compete power plant technologies for each grid cell based on the least expensive option.  NLC is calculated by subtracting the Net Operational Value (NOV) of the proposed power plant from the cost of its interconnection to the grid to represent the potential deployment value.  Both the NOV parameter which incorporates many technology-specific values such as variable operations and maintenance costs, carbon price, heat rate, etc. and the interconnection cost parameter used for both electricity transmission and gas pipelines have variables that are accessible to the user for modification per time step.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Load packages"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cerf\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Conduct a run with CERF"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We will be exploring the main functionality of the `cerf` package using our built-in data which is meant for illustrative purposes only.  `cerf` runs using a single YAML configuration file that contains project and technology-specific settings, an electricity capacity expansion plan, and lmp zones pricing data which is described in detail in the docs [here](https://immm-sfa.github.io/cerf/).  Expansion plans and technology data are generally generated by models such as GCAM-USA which capture multi-sector dynamics that represent alternate futures based on scenario assumptions for socioeconomics, radiative forcing, etc. The `cerf` package also utilizes power plant siting suitability data at a 1km resolution over the CONUS, publically available data from EIA and HIFLD for transmission and pipeline infrastructure, and 8760 locational marginal pricing from your prefered grid operations model.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Get up and running right away!\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Run `cerf` to site power plants in an expansion plan for a single year for the CONUS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2021-07-19 17:58:48,642 - root - INFO - Starting CERF model\n",
      "2021-07-19 17:58:48,831 - root - INFO - Staging data...\n",
      "2021-07-19 17:58:49,051 - root - INFO - Using 'zones_raster_file':  /Users/d3y010/repos/github/cerf/cerf/data/lmp_zones_1km.img\n",
      "2021-07-19 17:58:49,087 - root - INFO - Processing locational marginal pricing (LMP)\n",
      "2021-07-19 17:58:49,088 - root - INFO - Using LMP from default illustrative package data:  /Users/d3y010/repos/github/cerf/cerf/data/illustrative_lmp_8760-per-zone_dollars-per-mwh.zip\n",
      "2021-07-19 17:58:57,039 - root - INFO - Calculating interconnection costs (IC)\n",
      "2021-07-19 17:58:57,410 - root - INFO - Calculating net operational cost (NOV)\n",
      "2021-07-19 17:58:58,374 - root - INFO - Calculating net locational cost (NLC)\n",
      "2021-07-19 17:58:58,826 - root - INFO - Building suitability array\n",
      "2021-07-19 17:58:59,188 - root - INFO - Using suitability file for 'biomass_conv_wo_ccs':  /Users/d3y010/repos/github/cerf/cerf/data/suitability_biomass.sdat\n",
      "2021-07-19 17:58:59,224 - root - INFO - Using suitability file for 'coal_conv_pul_wo_ccs':  /Users/d3y010/repos/github/cerf/cerf/data/suitability_coal.sdat\n",
      "2021-07-19 17:58:59,257 - root - INFO - Using suitability file for 'gas_cc_w_ccs':  /Users/d3y010/repos/github/cerf/cerf/data/suitability_gas_cc_ccs.sdat\n",
      "2021-07-19 17:58:59,284 - root - INFO - Using suitability file for 'gas_cc_wo_ccs':  /Users/d3y010/repos/github/cerf/cerf/data/suitability_gas_cc.sdat\n",
      "2021-07-19 17:58:59,312 - root - INFO - Using suitability file for 'nuclear_gen_ii':  /Users/d3y010/repos/github/cerf/cerf/data/suitability_nuclear.sdat\n",
      "2021-07-19 17:58:59,342 - root - INFO - Using suitability file for 'oil_ct_wo_ccs':  /Users/d3y010/repos/github/cerf/cerf/data/suitability_oil_baseload.sdat\n",
      "2021-07-19 17:58:59,373 - root - INFO - Using suitability file for 'solar_csp':  /Users/d3y010/repos/github/cerf/cerf/data/suitability_solar.sdat\n",
      "2021-07-19 17:58:59,403 - root - INFO - Using suitability file for 'solar_pv_non_dist':  /Users/d3y010/repos/github/cerf/cerf/data/suitability_solar.sdat\n",
      "2021-07-19 17:58:59,431 - root - INFO - Using suitability file for 'wind_onshore':  /Users/d3y010/repos/github/cerf/cerf/data/suitability_wind.sdat\n",
      "2021-07-19 17:58:59,460 - root - INFO - Staged data in 10.6286049 seconds\n",
      "2021-07-19 17:59:00,142 - root - INFO - Processed `alabama` in 0.6814847 seconds\n",
      "2021-07-19 17:59:00,788 - root - INFO - Processed `arizona` in 0.644774 seconds\n",
      "2021-07-19 17:59:01,194 - root - INFO - Processed `arkansas` in 0.4054201 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "INFO:root:\n",
      "Unfortunately, your original traceback can not be constructed.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "INFO:root:\n",
      "Unfortunately, your original traceback can not be constructed.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-03fd24147656>\", line 8, in <module>\n",
      "    result_df = cerf.run(config_file, write_output=False)\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process.py\", line 187, in run\n",
      "    df = cerf_parallel(model=model,\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process.py\", line 85, in cerf_parallel\n",
      "    results = Parallel(n_jobs=n_jobs, backend=method)(delayed(process_state)(target_state_name=i,\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 1044, in __call__\n",
      "    while self.dispatch_one_batch(iterator):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 859, in dispatch_one_batch\n",
      "    self._dispatch(tasks)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 777, in _dispatch\n",
      "    job = self._backend.apply_async(batch, callback=cb)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n",
      "    result = ImmediateResult(func)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/_parallel_backends.py\", line 572, in __init__\n",
      "    self.results = batch()\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 262, in __call__\n",
      "    return [func(*args, **kwargs)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 262, in <listcomp>\n",
      "    return [func(*args, **kwargs)\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process_state.py\", line 328, in process_state\n",
      "    process = ProcessState(settings_dict=settings_dict,\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process_state.py\", line 119, in __init__\n",
      "    self.run_data = self.competition()\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process_state.py\", line 226, in competition\n",
      "    comp = Competition(target_state_name=self.target_state_name,\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/compete.py\", line 135, in __init__\n",
      "    self.sited_array, self.sited_df = self.compete()\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/compete.py\", line 166, in compete\n",
      "    tech = np.where(self.cheapest_arr_1d == tech_index)[0]\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/inspect.py\", line 1541, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/inspect.py\", line 1499, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/inspect.py\", line 709, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/inspect.py\", line 755, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/posixpath.py\", line 391, in realpath\n",
      "    path, ok = _joinrealpath(filename[:0], filename, {})\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/posixpath.py\", line 424, in _joinrealpath\n",
      "    newpath = join(path, name)\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/posixpath.py\", line 85, in join\n",
      "    elif not path or path.endswith(sep):\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-03fd24147656>\", line 8, in <module>\n",
      "    result_df = cerf.run(config_file, write_output=False)\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process.py\", line 187, in run\n",
      "    df = cerf_parallel(model=model,\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process.py\", line 85, in cerf_parallel\n",
      "    results = Parallel(n_jobs=n_jobs, backend=method)(delayed(process_state)(target_state_name=i,\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 1044, in __call__\n",
      "    while self.dispatch_one_batch(iterator):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 859, in dispatch_one_batch\n",
      "    self._dispatch(tasks)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 777, in _dispatch\n",
      "    job = self._backend.apply_async(batch, callback=cb)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n",
      "    result = ImmediateResult(func)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/_parallel_backends.py\", line 572, in __init__\n",
      "    self.results = batch()\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 262, in __call__\n",
      "    return [func(*args, **kwargs)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 262, in <listcomp>\n",
      "    return [func(*args, **kwargs)\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process_state.py\", line 328, in process_state\n",
      "    process = ProcessState(settings_dict=settings_dict,\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process_state.py\", line 119, in __init__\n",
      "    self.run_data = self.competition()\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process_state.py\", line 226, in competition\n",
      "    comp = Competition(target_state_name=self.target_state_name,\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/compete.py\", line 135, in __init__\n",
      "    self.sited_array, self.sited_df = self.compete()\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/compete.py\", line 166, in compete\n",
      "    tech = np.where(self.cheapest_arr_1d == tech_index)[0]\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3458, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2063, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/inspect.py\", line 1541, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/inspect.py\", line 1499, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/inspect.py\", line 709, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/inspect.py\", line 755, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/posixpath.py\", line 391, in realpath\n",
      "    path, ok = _joinrealpath(filename[:0], filename, {})\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/posixpath.py\", line 439, in _joinrealpath\n",
      "    path, ok = _joinrealpath(path, os.readlink(newpath), seen)\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/posixpath.py\", line 427, in _joinrealpath\n",
      "    continue\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "INFO:root:\n",
      "Unfortunately, your original traceback can not be constructed.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-03fd24147656>\", line 8, in <module>\n",
      "    result_df = cerf.run(config_file, write_output=False)\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process.py\", line 187, in run\n",
      "    df = cerf_parallel(model=model,\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process.py\", line 85, in cerf_parallel\n",
      "    results = Parallel(n_jobs=n_jobs, backend=method)(delayed(process_state)(target_state_name=i,\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 1044, in __call__\n",
      "    while self.dispatch_one_batch(iterator):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 859, in dispatch_one_batch\n",
      "    self._dispatch(tasks)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 777, in _dispatch\n",
      "    job = self._backend.apply_async(batch, callback=cb)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n",
      "    result = ImmediateResult(func)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/_parallel_backends.py\", line 572, in __init__\n",
      "    self.results = batch()\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 262, in __call__\n",
      "    return [func(*args, **kwargs)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/joblib/parallel.py\", line 262, in <listcomp>\n",
      "    return [func(*args, **kwargs)\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process_state.py\", line 328, in process_state\n",
      "    process = ProcessState(settings_dict=settings_dict,\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process_state.py\", line 119, in __init__\n",
      "    self.run_data = self.competition()\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/process_state.py\", line 226, in competition\n",
      "    comp = Competition(target_state_name=self.target_state_name,\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/compete.py\", line 135, in __init__\n",
      "    self.sited_array, self.sited_df = self.compete()\n",
      "  File \"/Users/d3y010/repos/github/cerf/cerf/compete.py\", line 166, in compete\n",
      "    tech = np.where(self.cheapest_arr_1d == tech_index)[0]\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3458, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2063, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2944, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3169, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3380, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2063, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/d3y010/.pyenv/versions/py3.9.4_cerf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/inspect.py\", line 1541, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/inspect.py\", line 1499, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/inspect.py\", line 709, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/inspect.py\", line 755, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/posixpath.py\", line 391, in realpath\n",
      "    path, ok = _joinrealpath(filename[:0], filename, {})\n",
      "  File \"/Users/d3y010/.pyenv/versions/3.9.4/lib/python3.9/posixpath.py\", line 411, in _joinrealpath\n",
      "    name, _, rest = rest.partition(sep)\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "# sample year\n",
    "yr = 2010\n",
    "\n",
    "# load the sample configuration file path for the target year\n",
    "config_file = cerf.config_file(yr)\n",
    "\n",
    "# run the configuration for the target year and return a data frame\n",
    "result_df = cerf.run(config_file, write_output=False)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### `cerf` results are returned as a Pandas DataFrame"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Each record is a sited power plant having a geographic location and other siting attributes. Reminder:  `cerf` uses the USA_Contiguous_Albers_Equal_Area_Conic projected coordinate reference system, so the `xcoord` and `ycoord` are relative to that projection.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "result_df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Run `cerf` to site power plants in an expansion plan for multiple years for the CONUS"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "This exercise demonstrates how to inherit sites from a previous year's results and keep them in the mix if they have not yet reached retirement.  If this is done in `cerf`, users should ensure that their expansion plan is only for new vintage each timestep.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cerf\n",
    "\n",
    "# process year 2010 and 2050\n",
    "for index, yr in enumerate([2010, 2050]):\n",
    "\n",
    "    print(f\"\\nProcessing year:  {yr}\")\n",
    "\n",
    "    # load the sample configuration file path for the target year\n",
    "    config_file = cerf.config_file(yr)\n",
    "\n",
    "    # do not intialize the run with previously sited data if it is the first time step\n",
    "    if index == 0:\n",
    "        result_df = cerf.run(config_file, write_output=False)\n",
    "\n",
    "    else:\n",
    "        result_df = cerf.run(config_file,\n",
    "                                 write_output=False,\n",
    "                                 initialize_site_data=result_df)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Explore the results that account for retirement"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Since we inherited the each year, and we are only siting new vintage per year, we see power plants from multiple technlogies until they reach their retirement age.  We can narrow in on `biomass` power plants in Virginia to see this:\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "result_df.loc[(result_df['state_name'] == 'virginia') & (result_df['tech_id'] == 9)]\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Plot the output"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "cerf.plot_siting(result_df)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "py3.9.4_cerf",
   "language": "python",
   "name": "py3.9.4_cerf"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
